<?php

namespace AppBundle\Repository;

/**
 * AccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get validateAccountDetails
     *
     * @return \AccountId
     */
    public function validateAccountDetails($accountNumber,$mobileNumber)
    {
       
       $accountId       =  null;
       $accountDetails  =  $this->findOneBy([
				                    'accountNumber'    => $accountNumber,
				                    'mobileNumber'     => $mobileNumber,
				                    'status'           => 1
				                ]);

       if($accountDetails != null) {
            $accountId  = intval($accountDetails->getId()); 
		}	 

        return $accountId;       

    }

}