<?php

namespace AppBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{

   /**
     * Get validateAccountDetails
     *
     * @return \AccountId
     */
    public function getAccountBalance($accountId)
    {
            //set balance amount
            $balanceAmount  = 0.00;
            //get the max account id from Account table
            $balance = $this->findOneBy(['accountId' => $accountId],['id'=>'desc']);
            
            //Get the max account number
            if ($balance != null) {
                $balanceAmount  = floatval($balance->getBalanceAmount());            
            }  

            return $balanceAmount;
            
    }


    /**
     * Get validateAccountDetails
     *
     * @return \AccountId
     */
    public function getLastFiveTransactions($accountId)
    {
        $transactions = $this->findBy(['accountId' => $accountId],['id'=>'desc'], 5);
        $statement = array(); 

        foreach ($transactions as $key => $transaction) {
                 $credit   = $transaction->getCreditAmount();
                 $debit    = $transaction->getDebitAmount();
                 $balance  = $transaction->getBalanceAmount();
                 $date     = $transaction->getTransactionDate();
                 $statement[] =  array($key+1,$credit,$debit,$balance);       
          }

          return $statement;            
    }


}